module.exports = {
  EQUIPMENT_NOT_FOUND: "EQU-001",
  NO_FILES_UPLOADED: "EQU-002",
  ATTACHMENT_NOT_FOUND: "EQU-003",
  BRAND_NOT_FOUND: "EQU-004",
  DUPLICATE_BRAND_NAME: "EQU-005",
  MODEL_NOT_FOUND: "EQU-006",
  DUPLICATE_MODEL_NAME: "EQU-007",
  TYPE_NOT_FOUND: "EQU-008",
  DUPLICATE_TYPE_NAME: "EQU-009"
}
