module.exports = {
  EQUIPMENT_NOT_FOUND: "EQU-001",
  NO_FILES_UPLOADED: "EQU-002",
  ATTACHMENT_NOT_FOUND: "EQU-003",
  BRAND_NOT_FOUND: "EQU-004",
  DUPLICATE_BRAND_NAME: "EQU-005",
  MODEL_NOT_FOUND: "EQU-006",
  DUPLICATE_MODEL_NAME: "EQU-007",
  TYPE_NOT_FOUND: "EQU-008",
  DUPLICATE_TYPE_NAME: "EQU-009",
  DUPLICATE_SN: "EQU-010",
  MODEL_NOT_MATCH_BRAND: "EQU-011",
  EQUIPMENTS_ASSOCIATED_WITH_BRAND: "EQU-012",
  EQUIPMENTS_ASSOCIATED_WITH_MODEL: "EQU-013",
  EQUIPMENTS_ASSOCIATED_WITH_TYPE: "EQU-014"
}
