module.exports = {
  USERNAME_ALREADY_EXISTS: "USR-001",
  EMAIL_ALREADY_EXISTS: "USR-002",
  USER_NOT_FOUND: "USR-003",
  USER_NOT_ACTIVE: "USR-004",
  PASSWORD_MISMATCH: "USR-005",
  AUTHENTICATION_FAILED: "USR-006",
  INVALID_TOKEN: "USR-007",
  TOKEN_NOT_PROVIDED: "USR-008",
  INVALID_REFRESH_TOKEN: "USR-009",
  REFRESH_TOKEN_NOT_PROVIDED: "USR-010",
  ERROR_GENERATING_TOKEN: "USR-011",
  USER_NOT_AUTHENTICATED: "USR-012",
  INVALID_OTP_CODE: "USR-013",
  INVALID_RESET_PASSWORD_CODE: "USR-014",
  USER_AVATAR_IS_REQUIRED: "USR-015",
  USER_NOT_ACTIVE_MIDDLEWARE: "USR-016"
}
